woodpecker_version: "v3.4.0"
db_user: "woodpecker"
db_name: "woodpecker"
db_password: "woodpecker"
postgresql_data_dir: "/var/lib/pgsql/data"
agent_secret: "{{ lookup('password', '/dev/null length=32 chars=hexdigits') }}"
gitea_client_id: "0b7a4e5e-1ee5-4a17-938a-4039e278cf4f"
gitea_client_secret: "gto_xentshbtspk4o3y36hddidsq4pmostf4h3z4u2m4m56zlbn46qfq"
