- name: Upload latest local backup
  hosts: alt

  vars:
    local_backup_dir: "~/backups"
    remote_backup_dir: "/opt/backups"

  tasks:
    - name: Check local backups
      delegate_to: localhost
      become: false
      shell: "ls -la {{ local_backup_dir }}/full_backup_*.tar.gz || echo 'NO_BACKUPS'"
      register: local_backups
      changed_when: false

    - name: Fail when no backups find locally
      fail:
        msg: "No backups in {{ local_backup_dir }}"
      when: "'NO_BACKUPS' in local_backups.stdout"

    - name: Fetch latest local backup
      delegate_to: localhost
      become: false
      shell: "ls -t {{ local_backup_dir }}/full_backup_*.tar.gz | head -n 1"
      register: latest_local_backup
      changed_when: false


    - name: Upload backup
      become: true
      become_method: su
      copy:
        src: "{{ latest_local_backup.stdout }}"
        dest: "{{ remote_backup_dir }}/{{ latest_local_backup.stdout | basename }}"
        mode: 0644
      when: latest_local_backup.stdout != ""
