- name: Perform system backup
  hosts: alt
  become: true
  become_method: su

  tasks:
      - name: Execute backup script
        command: /bin/bash /opt/backups/{{ module }}/{{ module }}_backup.sh
        register: backup_result
        changed_when: false
