- hosts: alt
  become: true
  become_method: su
  vars_files:
      - ../group_vars/postgres_vars.yml
      - ../group_vars/vault.yml
  vars:
      db_user: "{{ db_user }}"
      db_password: "{{ db_password }}"
      db_name: "{{ db_name }}"
  tasks:
      - name: Utility present
        ansible.builtin.package:
            name: python3-module-psycopg2
            state: latest

      - name: Create db user
        community.postgresql.postgresql_user:
            state: present
            name: "{{ db_user }}"
            password: "{{ db_password }}"
            role_attr_flags: LOGIN

      - name: Create db
        community.postgresql.postgresql_db:
            state: present
            name: "{{ db_name }}"
            owner: "{{ db_user }}"
            template: template0
            encoding: UTF8
            lc_collate: "en_US.UTF-8"
            lc_ctype: "en_US.UTF-8"

      - name: Check if {{ db_user }} have access to {{ db_name }}
        community.postgresql.postgresql_query:
            db: "{{ db_name }}"
            login_host: localhost
            login_user: "{{ db_user }}"
            login_password: "{{ db_password }}"
            query: "SELECT 1"
        register: db_check

      - name: Define {{ db_user }} access to {{ db_name }} if undefined
        lineinfile:
            state: present
            path: "{{ postgresql_data_dir }}/pg_hba.conf"
            line: "local    {{ db_name }}    {{ db_user }}    scram-sha-256"
        when: db_check.query_result[0][0] != 1

      - name: Restart postgresql
        ansible.builtin.systemd:
            name: postgresql
            state: restarted
