---
- hosts: alt
  become: true
  become_method: su
  vars_files:
      - ../group_vars/woodpecker_vars.yml
      - ../group_vars/postgres_vars.yml
      - ../group_vars/vault.yml
  tasks:
      - name: Include database configuration tasks
        ansible.builtin.include_tasks: ../roles/postgresql/tasks/configure-db.yml
        vars:
            db_user: "{{ woodpecker_db_user }}"
            db_password: "{{ woodpecker_db_password }}"
            db_name: "{{ woodpecker_db_name }}"
