- name: Deploy backup system
  hosts: alt
  become: true
  become_method: su

  tasks:
    - name: Create backup directory
      file:
        path: /opt/backups
        state: directory
        mode: 0775
        owner: root
        group: root

    - name: Deploy backup script
      copy:
        src: ../roles/backup/files/backup.sh
        dest: /opt/backups/backup.sh
        mode: 0755
        owner: root
        group: root

    - name: Deploy restore script
      copy:
        src: ../roles/backup/files/restore.sh
        dest: /opt/backups/restore.sh
        mode: 0755
        owner: root
        group: root
