- name: Deploy backup system
  hosts: alt
  become: true
  become_method: su

  tasks:
      - name: Update cache and install unzip
        apt_rpm:
            name: unzip
            state: latest
            update_cache: yes

      - name: Create backup group
        group:
            name: backup
            state: present

      - name: Add users to group
        user:
            name: "{{ item }}"
            groups: backup
            append: yes
        loop:
            - gitea
            - woodpecker
            - root
            - postgres

      - name: Create backups directories
        file:
            path: "{{ item }}"
            state: directory
            mode: 0775
            owner: root
            group: backup
        with_items:
            - /var/backups
            - /var/backups/gitea
            - /var/backups/woodpecker
            - /opt/backups/gitea
            - /opt/backups/woodpecker

      - name: Deploy backup scripts
        copy:
            src: "../roles/backup/files/{{ item }}_backup.sh"
            dest: "/opt/backups/{{ item }}/{{ item }}_backup.sh"
            mode: 0755
            owner: root
            group: backup
        with_items:
            - gitea
            - woodpecker

      - name: Deploy restore scripts
        copy:
            src: "../roles/backup/files/{{ item }}_restore.sh"
            dest: "/opt/backups/{{ item }}/{{ item }}_restore.sh"
            mode: 0755
            owner: root
            group: backup
        with_items:
            - gitea
            - woodpecker
