- name: Install and configure Gitea
  hosts: alt
  vars:
      module: gitea

- import_playbook: install-postgres.yml
  tags: gitea

- import_playbook: configure-gitea-db.yml
  tags: gitea

- import_playbook: install-gitea.yml
  tags: gitea

- import_playbook: deploy_backups_system.yml
  vars:
      module: gitea
  tags: gitea
