- name: Install and configure Woodpecker CI with Gitea integration
  hosts: alt
  become: true
  become_method: su
  vars_files:
      - ../group_vars/woodpecker_vars.yml
      - ../group_vars/host_vars.yml
      - ../group_vars/vault.yml
  tasks:
      - name: Install required packages
        apt_rpm:
            name: ["tar", "wget", "docker-engine"]
            state: latest
            update_cache: yes

      - name: Create woodpecker user
        user:
            name: woodpecker
            system: yes
            home: /var/lib/woodpecker
            shell: /sbin/nologin

      - name: Add woodpecker user to docker group
        user:
            name: woodpecker
            groups: docker
            append: yes

      - name: Create directories
        file:
            path: "{{ item }}"
            state: directory
            owner: woodpecker
            group: woodpecker
            mode: 0755
        with_items:
            - /opt/woodpecker

      - name: Upload installation script
        become: true
        become_method: su
        copy:
            src: "../roles/woodpecker/files/install-woodpecker.sh"
            dest: "/opt/woodpecker/install.sh"
            mode: 0744

      - name: Execute installation script
        command: /bin/bash /opt/woodpecker/install.sh

      - name: Configure Woodpecker Server
        template:
            src: ../roles/woodpecker/templates/woodpecker-server.env.j2
            dest: /etc/woodpecker/woodpecker-server.env
            owner: woodpecker
            group: woodpecker
            mode: 0640

      - name: Configure Woodpecker Agent
        template:
            src: ../roles/woodpecker/templates/woodpecker-agent.env.j2
            dest: /etc/woodpecker/woodpecker-agent.env
            owner: woodpecker
            group: woodpecker
            mode: 0640

      - name: Create systemd service for Server
        template:
            src: ../roles/woodpecker/templates/woodpecker-server.service.j2
            dest: /usr/local/lib/systemd/system/woodpecker-server.service
            mode: 0644

      - name: Create systemd service for Agent
        template:
            src: ../roles/woodpecker/templates/woodpecker-agent.service.j2
            dest: /usr/local/lib/systemd/system/woodpecker-agent.service
            mode: 0644

      - name: Enable and start services
        systemd:
            name: "{{ item }}"
            state: started
            enabled: yes
            daemon_reload: yes
        with_items:
            - woodpecker-server
            - woodpecker-agent
            - postgresql
            - docker
