- name: Restore from backup
  hosts: alt
  become: true
  become_method: su
  vars:
      backup_file: ""

  tasks:
      - name: Find latest backup if not specified
        shell: "ls -t /var/backups/{{ module }}/{{ module }}_backup_*.tar.gz | head -n1"
        register: latest_backup
        changed_when: false
        when: backup_file == ""

      - name: Set backup file path
        set_fact:
            final_backup_file: "{{ backup_file if backup_file != '' else latest_backup.stdout }}"

      - name: Fail if no backups found
        fail:
            msg: "No backup files found in /var/backups/{{ module }}"
        when: final_backup_file == ""

      - name: Execute restore script
        command: "/bin/bash /opt/backups/{{ module }}/{{ module }}_restore.sh {{ final_backup_file }}"
        register: restore_result
        changed_when: false
